config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :answers
  resources :questions

  devise_for :students, controllers: {
      confirmations: 'students/confirmations',
      registrations: 'students/registrations',
      passwords: 'students/passwords',
      sessions: 'students/sessions',
      unlocks: 'students/unlocks'
  }

  devise_for :faculties, controllers: {
      confirmations: 'faculties/confirmations',
      registrations: 'faculties/registrations',
      passwords: 'faculties/passwords',
      sessions: 'faculties/sessions',
      unlocks: 'faculties/unlocks'
  }

  devise_for :administrators, controllers: {
      confirmations: 'administrators/confirmations',
      registrations: 'administrators/registrations',
      passwords: 'administrators/passwords',
      sessions: 'administrators/sessions',
      unlocks: 'administrators/unlocks'
  }

  as :student do
    patch '/students/confirmation' => 'students/confirmations#update', :via => :patch, :as => :update_student_confirmation
  end

  as :faculty do
    patch '/faculties/confirmation' => 'faculties/confirmations#update', :via => :patch, :as => :update_faculty_confirmation
  end

  resources :courses do

    resources :students do
      get 'delete_student' => 'courses#delete_student_from_course'
    end

    resources :surveys do
      get 'send_new_survey_mail' => 'courses#send_new_survey_mail'

      get 'create_teams' => 'surveys#create_teams'

      put 'create_teams' => 'surveys#create_teams'

      get 'edit_team' => 'surveys#edit_teams'
      get 'remove_student' => 'surveys#remove_student'
      put 'edit_team' => 'surveys#edit_teams'

      get 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'
      post 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'

      get 'save_team' => 'surveys#save_team'
      get 'show_created_teams' => 'surveys#show_created_teams'
      get 'release_teams' => 'surveys#release_teams'

      get 'create_new_team' => 'surveys#create_new_team'

      get 'delete_team' => 'surveys#delete_team'
    end
  end

  resources :surveys, only: :none do
    resources :responses
  end

  resources :faculties
  resources :administrators

  get 'welcome/index'
  root 'welcome#index'

  get 'student/home' => 'students#home', :as => :student_home
  get 'faculty/home' => 'faculties#home', :as => :faculty_home

  get 'admin/home' => 'administrators#home', :as => :admin_home
  post 'admin/home' => 'administrators#home', :as => :admin_post_home

  get 'forgot_password' => 'welcome#forgot'

  get 'about' => 'welcome#about'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  ##
  # Index method
  ##
  def index
  end

  ##
  # Creates a new session
  ##
  def new
    @session = Session.new('')
  end

  ##
  # Login
  ##
  def login
  end

  ##
  # Forgot
  ##
  def forgot
  end

  ##
  # About
  ##
  def about
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="jumbotron center vertical-center">
  <h1>About Us!</h1>
  <br/>
  <h3>Team maker is an app that can be used to create surveys to build teams for any project or activity you may need.
  </h3>
  <h3>The teams are created based on the responses to the surveys that are made.</h3>
  <br/><br/>
</div>

app/views/welcome/index.html.erb
<% if administrator_signed_in? %>

    <script>
        window.location.href = "admin/home";
    </script>

<% elsif faculty_signed_in? %>

    <script>
        window.location.href = "faculty/home";
    </script>

<% elsif student_signed_in? %>

    <script>
        window.location.href = "student/home";
    </script>

<% else %>

    <div class="jumbotron center vertical-center">
      <h1>Welcome to Team Maker!</h1>

      <br/>
      <div>
        <h2>New Faculty Member?</h2>
        <div class="col-lg-12">
          <%= link_to 'Faculty Sign-up!', new_faculty_registration_path, :style => 'color:#FFFFFF;', :class => 'btn btn-primary' %>
        </div>
        <% #link_to 'Student Sign-up!', new_student_registration_path, :style => 'color:#FFFFFF;', :class => 'btn btn-primary'  %>
        <br/><br/>
      </div>
      <h3>Already have an account? Sign in!</h3>

      <div class="row">
        <div class="col">

          <%= link_to 'Admin Sign-in!', new_administrator_session_path, :style => 'color:#FFFFFF;', :class => 'btn btn-success' %>
        </div>
        <div class="col">
          <%= link_to 'Faculty Sign-in!', new_faculty_session_path, :style => 'color:#FFFFFF;', :class => 'btn btn-success' %>
        </div>

        <div class="col">
          <%= link_to 'Student Sign-in!', new_student_session_path, :style => 'color:#FFFFFF;', :class => 'btn btn-success' %>
        </div>

      </div>

      <br/><br/>
</div>

<% end %>

app/views/welcome/login.html.erb
<% provide(:title, 'Log in') %>
<div class="center">
  <h1>Log in</h1>
</div>
<br/>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <br/>

        <%= f.submit 'Log in', class: 'btn btn-primary' %>
    <% end %>

    <div class="center">
      <br/>
      <br/>
      <h4>New user?
        <br/><br/> <%= link_to 'Sign up now!', new_faculty_path, :style => 'color:#FFFFFF;', class: 'btn btn-danger' %>
      </h4></div>
  </div>
</div>