config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :answers
  resources :questions

  devise_for :students, controllers: {
      confirmations: 'students/confirmations',
      registrations: 'students/registrations',
      passwords: 'students/passwords',
      sessions: 'students/sessions',
      unlocks: 'students/unlocks'
  }

  devise_for :faculties, controllers: {
      confirmations: 'faculties/confirmations',
      registrations: 'faculties/registrations',
      passwords: 'faculties/passwords',
      sessions: 'faculties/sessions',
      unlocks: 'faculties/unlocks'
  }

  devise_for :administrators, controllers: {
      confirmations: 'administrators/confirmations',
      registrations: 'administrators/registrations',
      passwords: 'administrators/passwords',
      sessions: 'administrators/sessions',
      unlocks: 'administrators/unlocks'
  }

  as :student do
    patch '/students/confirmation' => 'students/confirmations#update', :via => :patch, :as => :update_student_confirmation
  end

  as :faculty do
    patch '/faculties/confirmation' => 'faculties/confirmations#update', :via => :patch, :as => :update_faculty_confirmation
  end

  resources :courses do

    resources :students do
      get 'delete_student' => 'courses#delete_student_from_course'
    end

    resources :surveys do
      get 'send_new_survey_mail' => 'courses#send_new_survey_mail'

      get 'create_teams' => 'surveys#create_teams'

      put 'create_teams' => 'surveys#create_teams'

      get 'edit_team' => 'surveys#edit_teams'
      get 'remove_student' => 'surveys#remove_student'
      put 'edit_team' => 'surveys#edit_teams'

      get 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'
      post 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'

      get 'save_team' => 'surveys#save_team'
      get 'show_created_teams' => 'surveys#show_created_teams'
      get 'release_teams' => 'surveys#release_teams'

      get 'create_new_team' => 'surveys#create_new_team'

      get 'delete_team' => 'surveys#delete_team'
    end
  end

  resources :surveys, only: :none do
    resources :responses
  end

  resources :faculties
  resources :administrators

  get 'welcome/index'
  root 'welcome#index'

  get 'student/home' => 'students#home', :as => :student_home
  get 'faculty/home' => 'faculties#home', :as => :faculty_home

  get 'admin/home' => 'administrators#home', :as => :admin_home
  post 'admin/home' => 'administrators#home', :as => :admin_post_home

  get 'forgot_password' => 'welcome#forgot'

  get 'about' => 'welcome#about'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessor :gpa_question, :comments_question, :team_creation_preference, :team_size
  belongs_to :course
  has_many :questions, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :students, through: :responses
  has_many :teams

  accepts_nested_attributes_for :questions,
                                reject_if: proc {|attributes| attributes['content'].blank?},
                                allow_destroy: true

  validates :name, presence: true
  validates :end_date, presence: true
  validates_associated :questions
  validate :priorities_must_be_unique, :one_gpa_and_comments_question, :end_date_must_be_in_future

  PRIORITY_MAX = 10


  def end_date_must_be_in_future
    if self.end_date < DateTime.now
      self.errors.add(:validation, "The survey's end date must not have already occurred.")
    end
  end

  def one_gpa_and_comments_question
    gpa_count = 0
    comments_count = 0

    self.questions.each do |question|
      gpa_count += 1 if question.content == Question::GPA
      comments_count += 1 if question.content == Question::COMMENTS
    end

    if gpa_count > 1
      self.errors.add(:validation, "Only one question can contain content of: 'What is your GPA?'.")
    end

    if comments_count > 1
      self.errors.add(:validation, "Only one question can contain content of: 'Comments'.")
    end
  end

  def priorities_must_be_unique
    priorities = []

    self.questions.each do |question|
      next if question.priority == 0

      if priorities.include? question.priority
        self.errors.add(:validation, 'Duplicate priority:  ' + question.priority.to_s + '. Please ensure priorities are unique (excluding 0).')
        break
      else
        priorities << question.priority
      end

    end
  end

  def get_survey_progress
    survey_progress = 0

    self.responses.each do |response|
      survey_progress += 1 if response.completed?
    end

    survey_progress.to_s + '/' + self.responses.count.to_s
  end

  def gpa_priority
    Question.find_by(survey_id: self.id, content: self.gpa_question).priority
  end

  def gpa_priority=(value)
    question = Question.find_by(survey_id: self.id, content: self.gpa_question)
    question.priority = value
    self.questions << question
  end

  def is_survey_complete?

    complete = true

    self.responses.each do |response|

      unless response.completed?
        complete = false
      end

    end

    complete
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :create_survey, only: [:create]
  before_action :update_survey, only: [:update]
  before_action :authenticate_higher_level!


  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @course = Course.find(params[:course_id])
  end

  # GET /surveys/new
  def new
    @course = Course.find(params[:course_id])
    @survey = @course.surveys.build
    @survey.gpa_question = Question.new(content: Question::GPA)
    @survey.comments_question = Question.new(content: Question::COMMENTS)
  end

  # GET /surveys/1/edit
  def edit
    @course = Course.find(params[:course_id])
    @survey.gpa_question = Question.find_by(survey_id: @survey.id, content: Question::GPA)
    @survey.comments_question = Question.find_by(survey_id: @survey.id, content: Question::COMMENTS)
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey.start_date = nil

    if @survey.errors.empty?
      add_student_to_survey
      @survey.questions << @survey.gpa_question
      @survey.questions << @survey.comments_question
    end

    @survey.start_date = nil

    respond_to do |format|
      if @survey.errors.empty? && @survey.save
        format.html {redirect_to course_path(@course), notice: 'Survey was successfully created.'}
        format.json {render :show, status: :created, location: @survey}
      else
        format.html {render :new}
        format.json {render json: @survey.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.errors.empty? && @survey.update(survey_params)
        format.html {redirect_to course_path(@course), notice: 'Survey was successfully updated.'}
        format.json {render :show, status: :ok, location: @survey}
      else
        flash[:error] = @survey.errors
        format.html {redirect_to :back}
        format.json {render json: @survey.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @course = Course.find(params[:course_id])
    @survey.destroy
    respond_to do |format|
      format.html {redirect_to @course, notice: 'Survey was successfully destroyed.'}
      format.json {head :no_content}
    end
  end


  def get_remaining
    @remaining.length
  end


  def create_teams

    @survey = Survey.find(params[:survey_id])

    $teams = Array.new
    @@teams = Array.new
    @instance_teams = Array.new

    @remaining = Array.new

    $remaining = Array.new

    $last_index = 0

    @responses = @survey.responses.select {|response| response.completed?}

    incomplete_responses = @survey.responses.select {|response| !response.completed?}
    team_size = params[:team_size].to_i
    preference = params[:team_creation_preference]

    incomplete_responses.each do |response|
      @remaining << response.student
    end

    if preference == 'Similar'
      create_teams_similar(1, @responses, team_size)

      $last_index = $teams.size-1

      create_teams_dissimilar(team_size)

    elsif preference == 'Dissimilar'

      create_teams_dissimilar(team_size)

      $last_index = $teams.size - 1
      create_teams_similar(1, @responses, team_size)
    end

    @responses.each do |response|
      @remaining << response.student
      $remaining << response.student
    end

    redirect_to course_survey_show_created_teams_path
  end

  def create_test_teams(survey, preference, team_size)

    @survey = survey


    $teams = Array.new
    @@teams = Array.new
    @instance_teams = Array.new
    @remaining = Array.new

    $remaining = Array.new

    @responses = @survey.responses.select {|response| response.completed?}

    incomplete_responses = @survey.responses.select {|response| !response.completed?}
    incomplete_responses.each do |response|
      @remaining << response.student
      $remaining << response.student
    end

    if preference == 'Similar'
      create_teams_similar(1, @responses, team_size)

    elsif preference == 'Dissimilar'
      create_teams_dissimilar(team_size)
    end

    @responses.each do |response|
      @remaining << response.student
      $remaining << response.student
    end
    return @remaining
  end

  def create_teams_similar(priority, responses, team_size)

    if responses.empty? || priority > Survey::PRIORITY_MAX
      return
    end

    question_array = @survey.questions.select {|question| question.priority == priority}
    if (!question_array.nil?) && (!question_array.empty?)
      create_similar_from_priority(priority, question_array, responses, team_size)
    end
  end

  def create_similar_from_priority(priority, question_array, responses, team_size)

    question = question_array[0]
    responses_answers = question.answers.select {|answer| responses.include? answer.response}
    grouped_answers = responses_answers.group_by {|answer| answer.content}

    grouped_answers.each_value do |answers|
      if answers.count > team_size

        answers_responses = []
        answers.each {|answer| answers_responses << answer.response}
        create_teams_similar(priority+1, answers_responses, team_size)
        answers.delete_if {|answer| !answers_responses.include? answer.response}
      end

      if answers.count == team_size

        team_answers = answers.shift(team_size)
        team = Team.new(survey_id: @survey.id)

        team_answers.each do |answer|
          team.students << answer.response.student
          responses.delete(answer.response)
          @responses.delete(answer.response)

        end

        @@teams << team
        $teams << team
        @instance_teams << team

      end
    end
  end

  def create_teams_dissimilar(team_size)
    questions = @survey.questions.select {|question| question.priority != 0}
    questions.sort_by! {|question| question.priority}
    potential_teammates = []
    current_teammates = []
    tie_break = []
    counter = 0
    tie_break_depth = 0
    termination_count = @responses.size

    while @responses.size >= team_size && counter <= termination_count
      counter += 1

      current_teammates << 0

      questions_responses = create_questions_responses(questions, @responses)

      q = 0
      while q < questions_responses.size

        # Get the potential teammates for anyone currently on the team.
        questions_responses[q].size.times do |r|
          current_answer = questions_responses[q][r]

          current_teammates.each do |index|
            team_answer = questions_responses[q][index]

            if current_answer == (team_answer - 1) || current_answer == (team_answer + 1)
              potential_teammates << r
            end
          end
        end

        tie_break_depth += 1 unless tie_break.empty?

        # Filter potential_teammates by current_teammates
        filter_by_current_teammates(potential_teammates, current_teammates, q, questions_responses)

        # Filter potential_teammates by tie_break
        filter_by_tie_break(potential_teammates, tie_break) unless tie_break.empty?

        if potential_teammates.empty?
          unless tie_break.empty?
            current_teammates << tie_break[0]
            tie_break.clear
            q -= (1 + tie_break_depth)
            tie_break_depth = 0
          end

        elsif potential_teammates.size == 1
          current_teammates << potential_teammates[0]
          tie_break.clear
          q -= (1 + tie_break_depth)
          tie_break_depth = 0

        elsif potential_teammates.size > 1
          tie_break.clear

          potential_groups = potential_teammates.group_by {|teammate| questions_responses[q][teammate]}
          potential_groups.each_key do |key|
            group = potential_groups[key]

            if group.size == 1
              current_teammates << group[0]
              potential_teammates.delete(group[0])
              teammates_to_delete = []

              potential_teammates.each do |teammate|
                if questions_responses[q-1][teammate] == questions_responses[q-1][group[0]]
                  teammates_to_delete << teammate
                end
              end

              teammates_to_delete.each do |teammate|
                potential_teammates.delete(teammate)
                potential_groups.each_value do |values|
                  values.delete(teammate)
                end
              end

              potential_groups.delete(key)
            end

            if current_teammates.size == team_size
              break
            end
          end

          if all_greater_than_one(potential_groups)
            potential_groups.each_value do |value|
              tie_break = tie_break + value
            end
          end
        end

        if current_teammates.size == team_size
          team = Team.new(survey_id: @survey.id)

          current_teammates.each do |teammate|
            team.students << @responses[teammate].student
          end

          $teams << team
          remove_multiple_from_responses(current_teammates, questions_responses)
          current_teammates.clear
          tie_break.clear
          break
        end

        potential_teammates.clear

        q += 1

      end

      current_teammates.clear
      potential_teammates.clear

      unless current_teammates.empty?
        $remaining << @responses.delete_at(current_teammates[0]).student
        current_teammates.clear
      end
    end
  end

  def all_greater_than_one(potential_groups)
    greater_than_one = true

    if potential_groups.empty?
      greater_than_one = false
    else
      potential_groups.each_value do |group|
        if group.size < 2
          greater_than_one = false
        end
      end
    end

    greater_than_one
  end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for ([@course, @survey]), html: {class: 'form-horizontal'} do |f| %>

    <div>

      <h4><br/> To create a survey enter as many courses as you'd like. You may also set up to 10 priorities for these
        questions which will be used to build your teams.
        <br/><br/><b> Please do not enter the same priority twice as this will cause team making to be done incorrectly
        and may result in no teams being created.</b> <br/><br/></h4>
      <br/>
    </div>

    <% if flash[:error] %>
        <div id="error_explanation">
          <% errors = flash[:error] %>
          <h2><%= pluralize(errors.count, 'error') %> prohibited this survey from being saved:</h2>
          <ul>
            <% errors.each do |error, message| %>
                <li><%= message.to_s %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if @survey.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@survey.errors.count, 'error') %> prohibited this survey from being saved:</h2>
          <ul>
            <% @survey.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :end_date, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.datetime_select :end_date, class: 'form-control' %>
      </div>
    </div>

    <br/>
    <h2>Questions</h2>

    <%= f.fields_for :gpa_question, @survey.gpa_question do |question| %>

        <div class="form-group">
          <%= question.label 'GPA', class: 'col-sm-2 control-label' %>
          <div class="col-sm-6">
            <%= question.text_field :content, readonly: true, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= question.label 'Priority', class: 'col-sm-2 control-label' %>
          <div class="col-sm-6">

            <%= question.select(:priority, Question::PRIORITIES, class: 'form-control') %>
          </div>
        </div>

    <% end %>

    <%= f.fields_for :comments_question, @survey.comments_question do |question| %>

        <div class="form-group">
          <%= question.label 'Comments', class: 'col-sm-2 control-label' %>
          <div class="col-sm-6">
            <%= question.text_area :content, readonly: true, class: 'form-control textarea', size: '10x5' %>
          </div>
        </div>

    <% end %>

    <br/>
    <h3>Course Grades</h3>

    <div id="course_questions">
      <%= f.fields_for :questions do |question| %>
          <% next if (question.object.content == @survey.gpa_question.content || question.object.content == @survey.comments_question.content) %>

          <%= render 'question_fields', f: question %>
      <% end %>
      <br/>
      <div id="links">
        <%= link_to_add_association 'Add Course', f, :questions, class: 'btn btn-primary' %>
      </div>
    </div>

    <br/>
    <div class="actions">
      <%= f.submit 'Submit Survey', class: 'btn btn-primary' %>
    </div>

    <br/><br/><br/>
    <div>
      <p><i>*A field that is read only means that it is a required question for all surveys.</i></p>
    </div>

<% end %>

app/views/surveys/_question_fields.html.erb
<div class="nested-fields" class="form-horizontal">

  <div class="form-group">
    <%= f.label :content, 'Course Name ', class: 'col-sm-2 control-label' %>

    <div class="col-sm-6">

      <%= f.text_field :content, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :priority, ' Priority ', class: 'col-sm-2 control-label' %>

    <div class="col-sm-6">

      <%= f.select(:priority, Question::PRIORITIES, class: 'form-control') %>

    </div>

    <%= link_to_remove_association 'Remove Question', f, class: 'btn btn-primary' %>
  </div>
</div>

app/views/surveys/create_new_team.html.erb
<%= form_tag(course_survey_create_new_team_path) %>


<h1>Hello World</h1>

app/views/surveys/create_teams.html.erb
<h1>Team Making Results</h1>

<div class="jumbotron center vertical-center">

  <h3>Teams</h3>

  <table class="table">

    <tr>
      <th class="text-center">Team Number</th>
      <th colspan="4" class="text-center">Students</th>
      <th class="text-center">Edit Team</th>
    </tr>

    <% @instance_teams.each_with_index do |team, index| %>

        <tr id=<%= index+1 %>>

          <td>Team <%= index+1 %></td>
          <td></td>
          <% if team.students.size == 2 %>

              <% team.students.each do |student| %>

                  <td> <%= mail_to student.email, student.name %> </td>

              <% end %>

              <td></td>
          <% elsif team.students.size == 3 %>
              <% team.students.each do |student| %>

                  <td> <%= mail_to student.email, student.name %> </td>

              <% end %>


          <% end %>

          <td><%= link_to 'Edit Team', course_survey_edit_team_path(team_id: index) %></td>

    <% end %>
    </tr>

  </table>


</div>

<div class="jumbotron center vertical-center">

  <h3>Remaining Students</h3>

  <table class="table">

    <tr>

      <th class="text-center">Name</th>
      <th class="text-center">Email</th>

    </tr>

    <% @remaining.each do |remainingStudent| %>
        <td><%= remainingStudent.name %></td>
        <td><%= mail_to remainingStudent.email, remainingStudent.email %></td>
    <% end %>


  </table>


</div>

<!-- Select with selected being the member that was created. -->

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

app/views/surveys/edit_teams.html.erb
<div class="jumbotron center vertical-center">

  <h3>Team <%= params[:team_id].to_i + 1 %></h3>
  <br/>
  <table class="table">
    <tr>

      <th class="text-center">Team Member</th>
      <th class="text-center">Remove</th>
    </tr>

    <% @edited_team.students.each do |student| %>
        <tr>
          <td> <%= student.name %></td>
          <td> <%= link_to 'Remove Student',
                           course_survey_remove_student_path(student_id: student.id, team_id: @edited_team.id),
                           style: 'color:#FFFFFF', class: 'btn btn-danger' %></td>
        </tr>

    <% end %>

  </table>

  <td> <%= link_to 'Save Team', course_survey_save_team_path(team_id: @edited_team.id),
                   style: 'color: #FFFFFF', class: 'btn btn-success' %></td>

</div>

<div class="jumbotron center vertical-center">

  <%= form_tag(course_survey_add_student_to_team_from_form_path(team_id: @edited_team.id)) %>


  <h3>Add Student to team</h3>

  <div class="col-lg-12">

    <%= collection_select(:selected_student, :selected_student_email, @remainderStudents,
                          :email, :name, include_blank: true) %>

    <%= submit_tag 'Add Student', style: 'color#FFFFFF', class: 'btn btn-primary' %></div>
  <br/>
  <p>Use this drop down to add students to this team</p>

</div>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table class="table" style="text-align: center">
  <thead>
  <tr>
    <th class="text-center">Name</th>
    <th class="text-center">Start date</th>
    <th class="text-center">End date</th>
  </tr>
  </thead>

  <tbody>
  <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= survey.start_date %></td>
        <td><%= survey.end_date %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

app/views/surveys/release_teams.html.erb
<h2>

  Teams have been released.


</h2>

app/views/surveys/show.html.erb
<!--suppress ALL -->



<p id="notice"><%= notice %></p>


<div class="jumbotron center vertical-center">
  <h2><%= @survey.name %></h2>
  <table class="table" style="text-align: center">
    <tr>
      <td><h3>Started: <%= @survey.start_date.to_date %>  </h3></td>
      <td><h3>Ends: <%= @survey.end_date.to_date %></h3></td>
    </tr>

  </table>

  <h2>Questions</h2>
  <table class="table" style="text-align: center">
    <th class="text-center">Content</th>
    <th class="text-center">Priority</th>

    <% @survey.questions.reverse.each do |question| %>
        <tr>

          <td> <%= question.content %></td>
          <td> <%= question.priority %></td>

        </tr>


    <% end %>
  </table>

  <h3>Comments</h3>
  <table class="table" style="text-align: center; table-layout: fixed">
    <tr>
      <th class="text-center">Student Name</th>
      <th class="text-center">Comment</th>
    </tr>


    <% @survey.questions.select {|question| question.content == Question::COMMENTS}[0].answers.each do |answer| %>
        <tr>
          <td><%= mail_to answer.response.student.email, answer.response.student.name %></td>
          <td><%= answer.content %></td>
    <% end %>
    </tr>

  </table>
</div>


<% if @survey.end_date <= DateTime.now || @survey.is_survey_complete? %>


    <div class="jumbotron center vertical-center">

      <h1>Survey Teams</h1> <br/>


      <table class="table" style="text-align: center">

        <th class="text-center">Team Number</th>
        <th class="text-center">Team Members</th>
        <th></th>
        <th></th>
        <th></th>

        <% @survey.teams.each do |team| %>
            <tr>
              <td>
                <%= team.id %>
              </td>

              <% team.students.each do |student| %>

                  <td><%= student.name %></td>

              <% end %>

            </tr>

        <% end %>

      </table>
    </div>

    <div class="jumbotron center vertical-center">
      <% if @survey.teams.size <= 0 %>


          <%= form_tag(course_survey_create_teams_path(@course, @survey), method: :put) do %>

              <h2>Team Making Criteria</h2>
              <br/>
              <div class="col-sm-4">
                <%= radio_button_tag(:team_creation_preference, 'Similar') %>
                <%= label_tag(:team_creation_preference, 'Group Similar') %>
                <br/>
                <%= radio_button_tag(:team_creation_preference, 'Dissimilar') %>
                <%= label_tag(:team_creation_preference, 'Group Dissimilar') %>
              </div>

              <div class="col-sm-4">
                <%= label_tag(:team_size, 'Team Size') %>
                <%= select_tag(:team_size, options_for_select([2, 3, 4])) %>
              </div>

              <div class="col-sm-4">
                <%= submit_tag 'Create Teams', class: 'btn btn-primary' %>
              </div>
              <br/><br/><br/>
              <div class="col-lg-12">
                <h3>Use these options to change how the teams are made.</h3>
              </div>

          <% end %>


      <% else %>

          <h2> Teams have already been made! To make more teams, create a new survey! </h2>

      <% end %>
    </div>


<% else %>
    <div class="jumbotron center vertical-center">

      <h2>After the survey end date has passed or all the students have completed the survey,
        you will be able to make teams based off their answers and the priorities you set.</h2>

    </div>
<% end %>

app/views/surveys/show_created_teams.html.erb
<h1>Team Making Results</h1>

<div class="jumbotron center vertical-center">

  <h3>Teams</h3>

  <table class="table">

    <tr>
      <th class="text-center">Team index</th>
      <th colspan="4" class="text-center">Students</th>
      <th colspan="2" class="text-center">Team Actions</th>
    </tr>

    <% @teams.each_with_index do |team, index| %>

        <tr>

          <% if index > $last_index %>


              <td bgcolor="yellow"><%= index+1 %></td>
              <% team.students.each do |student| %>
                  <td bgcolor="yellow"><%= mail_to student.email, student.name %></td>
              <% end %>

          <% else %>

              <td><%= index+1 %></td>
              <% team.students.each do |student| %>
                  <td><%= mail_to student.email, student.name %></td>

              <% end %>

          <% end %>
          <% if team.students.size == 0 %>
              <td></td>
              <td></td>
              <td>No students yet</td>
              <td></td>

          <% elsif team.students.size == 1 %>
              <td></td>
              <td></td>
              <td></td>
          <% elsif team.students.size == 2 %>
              <td></td>
              <td></td>
          <% elsif team.students.size == 3 %>
              <td></td>
          <% end %>

          <% if !team.released %>
              <td><%= link_to 'Edit Team', course_survey_edit_team_path(team_id: index), style: 'color:#FFFFFF',
                              class: 'btn btn-primary' %></td>

              <td> <%= link_to 'Delete Team', course_survey_delete_team_path(team_id: index), style: 'color:#FFFFFF', class: 'btn btn-danger' %></td>

          <% else %>

              <td> <%= link_to 'Edit Team', course_survey_edit_team_path(team_id: index),
                               disabled: true, style: 'color:#FFFFFF',
                               class: 'btn btn-primary' %></td>
              <td> <%= link_to 'Delete Team', course_survey_delete_team_path(team_id: index),
                               style: 'color:#FFFFFF', class: 'btn btn-danger', disabled: true %></td>


          <% end %>
        </tr>

    <% end %>

    <% if @teams.all? {|team| !team.released} %>
        <%= link_to 'Create New Team', course_survey_create_new_team_path, style: 'color: #FFFFFF',
                    class: 'btn btn-primary' %><br/>
        <%= link_to 'Release Team Information', course_survey_release_teams_path, style: 'color: #FFFFFF', class: 'btn btn-success' %>
        <br/><br/>
    <% else %>
        <%= link_to 'Create New Team', course_survey_create_new_team_path,
                    style: 'color: #FFFFFF', class: 'btn btn-primary', disabled: true %><br/>
        <%= link_to 'Release Team Information', course_survey_release_teams_path,
                    style: 'color: #FFFFFF', class: 'btn btn-success', disabled: true %>
        <br/><br/>
    <% end %>

  </table>


</div>

<p><i>*If a team is highlighted, it means that team was formed through the opposite grouping option than you chose or is
  a team you created.</i></p>
<br/>
<br/>

<div class="jumbotron center vertical-center">

  <h3>Remaining Students</h3>

  <% if @remaining.size != 0 %>

      <table class="table">

        <tr>

          <th class="text-center">Name</th>
          <th class="text-center">Email</th>

        </tr>

        <% @remaining.each do |remainingStudent| %>
            <tr>
              <td><%= remainingStudent.name %></td>
              <td><%= mail_to remainingStudent.email, remainingStudent.email %></td>
            </tr>
        <% end %>


      </table>

  <% else %>

      <h3>No remaining students!</h3>
  <% end %>
</div>