config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :answers
  resources :questions

  devise_for :students, controllers: {
      confirmations: 'students/confirmations',
      registrations: 'students/registrations',
      passwords: 'students/passwords',
      sessions: 'students/sessions',
      unlocks: 'students/unlocks'
  }

  devise_for :faculties, controllers: {
      confirmations: 'faculties/confirmations',
      registrations: 'faculties/registrations',
      passwords: 'faculties/passwords',
      sessions: 'faculties/sessions',
      unlocks: 'faculties/unlocks'
  }

  devise_for :administrators, controllers: {
      confirmations: 'administrators/confirmations',
      registrations: 'administrators/registrations',
      passwords: 'administrators/passwords',
      sessions: 'administrators/sessions',
      unlocks: 'administrators/unlocks'
  }

  as :student do
    patch '/students/confirmation' => 'students/confirmations#update', :via => :patch, :as => :update_student_confirmation
  end

  as :faculty do
    patch '/faculties/confirmation' => 'faculties/confirmations#update', :via => :patch, :as => :update_faculty_confirmation
  end

  resources :courses do

    resources :students do
      get 'delete_student' => 'courses#delete_student_from_course'
    end

    resources :surveys do
      get 'send_new_survey_mail' => 'courses#send_new_survey_mail'

      get 'create_teams' => 'surveys#create_teams'

      put 'create_teams' => 'surveys#create_teams'

      get 'edit_team' => 'surveys#edit_teams'
      get 'remove_student' => 'surveys#remove_student'
      put 'edit_team' => 'surveys#edit_teams'

      get 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'
      post 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'

      get 'save_team' => 'surveys#save_team'
      get 'show_created_teams' => 'surveys#show_created_teams'
      get 'release_teams' => 'surveys#release_teams'

      get 'create_new_team' => 'surveys#create_new_team'

      get 'delete_team' => 'surveys#delete_team'
    end
  end

  resources :surveys, only: :none do
    resources :responses
  end

  resources :faculties
  resources :administrators

  get 'welcome/index'
  root 'welcome#index'

  get 'student/home' => 'students#home', :as => :student_home
  get 'faculty/home' => 'faculties#home', :as => :faculty_home

  get 'admin/home' => 'administrators#home', :as => :admin_home
  post 'admin/home' => 'administrators#home', :as => :admin_post_home

  get 'forgot_password' => 'welcome#forgot'

  get 'about' => 'welcome#about'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :faculties

  validates :name, presence: true
  validates :phone, presence: true
  validates :department, presence: true
  validates :university, presence: true

end

app/controllers/administrators/confirmations_controller.rb
class Administrators::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/administrators/omniauth_callbacks_controller.rb
class Administrators::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/administrators/passwords_controller.rb
class Administrators::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/administrators/registrations_controller.rb
class Administrators::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :department, :university])

=begin
   devise_parameter_sanitizer.permit(:sign_up) << :name
     devise_parameter_sanitizer.permit(:sign_up) << :phone
     devise_parameter_sanitizer.permit(:sign_up) << :department
     devise_parameter_sanitizer.permit(:sign_up) << :university
=end

  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :department, :university])

=begin
   devise_parameter_sanitizer.permit(:account_update) << :name
     devise_parameter_sanitizer.permit(:account_update) << :phone
     devise_parameter_sanitizer.permit(:account_update) << :department
     devise_parameter_sanitizer.permit(:account_update) << :university
=end

  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_in_path_for(resource)
    '/admin/home' # Or :prefix_to_your_route
  end
end

app/controllers/administrators/sessions_controller.rb
class Administrators::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    '/admin/home' # Or :prefix_to_your_route
  end

end

app/controllers/administrators/unlocks_controller.rb
class Administrators::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController

  before_action :authenticate_admin!
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  @unapprovedFaculty = Faculty.where(:approved => false)

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all

  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  def home
    @unapprovedFaculty = Faculty.where(:approved => false)

    self.approve_faculty
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  def approve_faculty

    @show_table = false
    @show_empty_message = false

    @unapprovedFaculty = Faculty.where(:approved => false)

    @allFaculty = Faculty.all

    if @unapprovedFaculty.empty?
      @show_empty_message = true
    else
      @show_table = true
    end

  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html {redirect_to @administrator, notice: 'Administrator was successfully created.'}
        format.json {render :show, status: :created, location: @administrator}
      else
        format.html {render :new}
        format.json {render json: @administrator.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html {redirect_to @administrator, notice: 'Administrator was successfully updated.'}
        format.json {render :show, status: :ok, location: @administrator}
      else
        format.html {render :edit}
        format.json {render json: @administrator.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html {redirect_to administrators_url, notice: 'Administrator was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_administrator
    @administrator = Administrator.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def administrator_params
    params.require(:administrator).permit(:name, :phone, :department, :university, :email, :encrypted_password, :faculty_ids => [])
  end

end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<h1>Administrator Sign up</h1>


<br/><br/>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'form-horizontal'}) do |f| %>

    <%= devise_error_messages! %>


    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :name, class: 'form-control', autofocus: true, :placeholder => 'Name' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :phone, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :phone, class: 'form-control', autofocus: true, :placeholder => 'Phone Number' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :department, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :department, class: 'form-control', autofocus: true, :placeholder => 'Department' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :university, class: 'col-sm-2 control-label' %>
      <div class="col-lg-6">

        <%= f.text_field :university, class: 'form-control', autofocus: true, :value => 'Georgia State University' %>

      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.email_field :email, class: 'form-control', autofocus: true, :placeholder => 'Email' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br/>
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off', :placeholder => 'Password' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.password_field :password_confirmation, class: 'form-control', autofocus: true, :placeholder => 'Password Confirmation' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit 'Sign up', class: 'btn btn-primary' %>
      </div>
    </div>

<% end %>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-6">
    <%= render 'administrators/shared/links' %>
  </div>
</div>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form' %>

app/views/administrators/home.html.erb
<div class="jumbotron center vertical-center">
  <h2>Faculty Requests</h2><br/>
  <% if @show_table %>
      <div>
        <%= form_for('approve_faculty') do |f| %>

            <table class="table table-responsive" style="text-align: center">
              <tr>
                <th class="text-center">Faculty Name</th>
                <th class="text-center">Phone</th>
                <th class="text-center">Department</th>
                <th class="text-center">University</th>
                <th class="text-center">Email</th>
                <th class="text-center">Approve</th>
              </tr>

              <% @unapprovedFaculty.each do |faculty| %>
                  <tr>
                    <td><%= faculty.name %></td>
                    <td> <%= faculty.phone %></td>
                    <td> <%= faculty.department %></td>
                    <td> <%= faculty.university %></td>
                    <td> <%= faculty.email %></td>
                    <td>  <%= link_to 'Click here to Approve', edit_faculty_path(faculty), :style => 'color:#FFFFFF;', :class => 'btn btn-primary' %>
                    </td>
                  </tr>
              <% end %>

            </table>
            </div>
            <br/><br/>
        <% end %>
  <% end %>

  <% if @show_empty_message %>
      <h3>No unapproved faculty! :) </h3>
  <% end %>
</div>


<div class="jumbotron center vertical-center">

  <h2>All Faculty</h2><br/>

  <table class="table table-responsive" style="text-align: center">

    <tr>
      <th class="text-center">Faculty Name</th>
      <th class="text-center">Phone</th>
      <th class="text-center">Department</th>
      <th class="text-center">University</th>
      <th class="text-center">Email</th>
      <th class="text-center">Approved?</th>
    </tr>

    <% @allFaculty.each do |faculty| %>
        <tr>
          <td><%= faculty.name %></td>
          <td> <%= faculty.phone %></td>
          <td> <%= faculty.department %></td>
          <td> <%= faculty.university %></td>
          <td> <%= faculty.email %></td>

          <% if faculty.approved? %>
              <td> Yes</td>
          <% else %>
              <td> No</td>
          <% end %>

        </tr>
    <% end %>
  </table>

</div>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Administrators</h1>

<table class="table" style="text-align: center">
  <thead>
  <tr>
    <th class="text-center">Name</th>
    <th class="text-center">Phone</th>
    <th class="text-center">Department</th>
    <th class="text-center">University</th>
    <th class="text-center">Password</th>
    <th class="text-center" colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.name %></td>
        <td><%= administrator.phone %></td>
        <td><%= administrator.department %></td>
        <td><%= administrator.university %></td>
        <td><%= administrator.password %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form' %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @administrator.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @administrator.phone %>
</p>

<p>
  <strong>Department:</strong>
  <%= @administrator.department %>
</p>

<p>
  <strong>University:</strong>
  <%= @administrator.university %>
</p>

<p>
  <strong>Password:</strong>
  <%= @administrator.password %>
</p>