config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :answers
  resources :questions

  devise_for :students, controllers: {
      confirmations: 'students/confirmations',
      registrations: 'students/registrations',
      passwords: 'students/passwords',
      sessions: 'students/sessions',
      unlocks: 'students/unlocks'
  }

  devise_for :faculties, controllers: {
      confirmations: 'faculties/confirmations',
      registrations: 'faculties/registrations',
      passwords: 'faculties/passwords',
      sessions: 'faculties/sessions',
      unlocks: 'faculties/unlocks'
  }

  devise_for :administrators, controllers: {
      confirmations: 'administrators/confirmations',
      registrations: 'administrators/registrations',
      passwords: 'administrators/passwords',
      sessions: 'administrators/sessions',
      unlocks: 'administrators/unlocks'
  }

  as :student do
    patch '/students/confirmation' => 'students/confirmations#update', :via => :patch, :as => :update_student_confirmation
  end

  as :faculty do
    patch '/faculties/confirmation' => 'faculties/confirmations#update', :via => :patch, :as => :update_faculty_confirmation
  end

  resources :courses do

    resources :students do
      get 'delete_student' => 'courses#delete_student_from_course'
    end

    resources :surveys do
      get 'send_new_survey_mail' => 'courses#send_new_survey_mail'

      get 'create_teams' => 'surveys#create_teams'

      put 'create_teams' => 'surveys#create_teams'

      get 'edit_team' => 'surveys#edit_teams'
      get 'remove_student' => 'surveys#remove_student'
      put 'edit_team' => 'surveys#edit_teams'

      get 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'
      post 'add_student_to_team_from_form' => 'surveys#add_student_to_team_from_form'

      get 'save_team' => 'surveys#save_team'
      get 'show_created_teams' => 'surveys#show_created_teams'
      get 'release_teams' => 'surveys#release_teams'

      get 'create_new_team' => 'surveys#create_new_team'

      get 'delete_team' => 'surveys#delete_team'
    end
  end

  resources :surveys, only: :none do
    resources :responses
  end

  resources :faculties
  resources :administrators

  get 'welcome/index'
  root 'welcome#index'

  get 'student/home' => 'students#home', :as => :student_home
  get 'faculty/home' => 'faculties#home', :as => :faculty_home

  get 'admin/home' => 'administrators#home', :as => :admin_home
  post 'admin/home' => 'administrators#home', :as => :admin_post_home

  get 'forgot_password' => 'welcome#forgot'

  get 'about' => 'welcome#about'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_faculty!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit

  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.faculty_id = current_faculty.id
    @file = params[:course][:file]

    if student_is_not_blank?
      add_single_student_to_course
    end

    if @file
      @course.parse_students(@file)
    end

    respond_to do |format|
      if @course.errors.empty? && @course.save
        format.html {redirect_to @course, notice: 'Course was successfully created.'}
        format.json {render :show, status: :created, location: @course}
      else
        format.html {render :new}
        format.json {render json: @course.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @file = params[:course][:file]

    if student_is_not_blank?
      add_single_student_to_course
    end

    if @file
      parse_students(@file)
    end

    respond_to do |format|
      if @course.errors.empty? && @course.update(course_params)
        format.html {redirect_to @course, notice: 'Course was successfully updated.'}
        format.json {render :show, status: :ok, location: @course}
      else
        format.html {render :edit}
        format.json {render json: @course.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html {redirect_to faculty_home_path, notice: 'Course was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def send_new_survey_mail

    course = Course.find(params[:course_id])
    survey = Survey.find(params[:survey_id])

    course.students.each do |currentStudent|
      NewSurveyMailer.send_new_survey_email(currentStudent, course, survey).deliver_now
    end

    survey.update(start_date: DateTime.now)

    respond_to do |format|
      format.html {redirect_to course_path(course), notice: 'Survey was successfully released'}
      format.json {head :no_content}
    end

  end

  def delete_student_from_course

    student = Student.find(params[:student_id])
    course = Course.find(params[:course_id])
    course.delete_student(student)

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(:name, :semester, :section, :faculty_id, :file, :survey_ids => [], :student_ids => [])
  end

  def parse_students(file)
    @course.parse_students(file)
  end


  def student_is_not_blank?
    return false if params[:course][:student].nil?
    name = params[:course][:student][:name]
    student_id = params[:course][:student][:student_id]
    email = params[:course][:student][:email]

    (name != '' || student_id != '' || email != '')
  end

  ##
  # Adds a single student to a course.
  ##
  def add_single_student_to_course
    begin
      student = Student.find_by_email(params[:course][:student][:email])

      if student.nil?
        student = Student.new
        student.email = params[:course][:student][:email]

        student.student_id = params[:course][:student][:student_id]
        student.name = params[:course][:student][:name]
        student.university = Faculty.find(@course.faculty_id).university
      end

      if student.invalid?
        raise StandardError
      end

      @course.surveys.each do |survey|
        survey.students << student
      end

      @course.students << student

    rescue
      @course.errors.add(:student, 'is invalid!')
      return
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for @course, :html => {:multipart => true, class: 'form-horizontal'} do |f| %>
    <% if @course.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@course.errors.count, 'error') %> prohibited this course from being saved:</h2>

          <ul>
            <% @course.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :name, class: 'form-control', autofocus: true, :placeholder => 'Name' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :semester, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :semester, class: 'form-control', :placeholder => 'Semester' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :section, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :section, class: 'form-control', :placeholder => 'Section' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :file, 'Student Data', class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.file_field :file, class: 'form-control', accept: '.csv' %>
      </div>
    </div>

    <br/><br/><br/>

    <h2> Add single student </h2>
    <br/>

    <%= f.fields_for :student do |builder| %>
        <%= render 'student_fields', :f => builder %>
    <% end %>


    <br/>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/courses/_student_fields.erb
<div class="form-group">
  <%= f.label :name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-6">
    <%= f.text_field :name, class: 'form-control', autofocus: true, :placeholder => 'Name' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :student_id, 'Student Id', class: 'col-sm-2 control-label' %>
  <div class="col-sm-6">
    <%= f.text_field :student_id, class: 'form-control', autofocus: true, :placeholder => 'Student ID' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :email, class: 'col-sm-2 control-label' %>
  <div class="col-sm-6">
    <%= f.email_field :email, class: 'form-control', autofocus: true, :placeholder => 'Email' %>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table class="table" style="text-align: center">
  <thead>
  <tr>
    <th class="text-center">Name</th>
    <th class="text-center">Semester</th>
    <th class="text-center">Section</th>
    <th class="text-center" colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.semester %></td>
        <td><%= course.section %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>
<br/>
<br/>
<%= render 'form' %>
<br/>
<br/>

app/views/courses/show.html.erb
<div class="center">
  <h1><%= @course.name %></h1>
</div>

<div class="jumbotron center vertical-center">
  <h2 class="center">Surveys</h2>
  <br/>
  <table class="table" style="text-align: center">

    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Start Date</th>
      <th class="text-center">End Date</th>
      <th class="text-center">Survey Progress</th>
      <th class="text-center" colspan="3">Survey Actions</th>
    </tr>

    <% @course.surveys.each do |survey| %>
        <tr>
          <td><%= survey.name %></td>
          <td> <%= survey.start_date %></td>
          <td> <%= survey.end_date %></td>
          <td><%= survey.get_survey_progress %></td>
          <% if survey.start_date.nil? %>
              <td>
                <%= link_to 'Edit', edit_course_survey_path(@course, survey), :style => 'color:#FFFFFF;', :class => 'btn btn-primary' %> </td>
              <td> <%= link_to 'Release', course_survey_send_new_survey_mail_path(@course, survey), style: 'color:#FFFFFF', class: 'btn btn-success' %>
              <td>  <%= link_to 'Destroy', course_survey_path(@course, survey), method: :delete, data: {confirm: 'Are you sure?'}, style: 'color:#FFFFFF', class: 'btn btn-danger' %> </td>

          <% else %>

              <td><%= link_to 'View', course_survey_path(@course, survey), style: 'color:#FFFFFF;', class: 'btn btn-primary' %></td>
              <td>  <%= link_to 'Destroy', course_survey_path(@course, survey), method: :delete, data: {confirm: 'Are you sure?'}, style: 'color:#FFFFFF', class: 'btn btn-danger' %> </td>


          <% end %>
        </tr>
    <% end %>

  </table>
</div>

<%= link_to 'New Survey', new_course_survey_path(@course), :class => 'btn btn-primary', :style => 'color:#FFFFFF; float: right' %>

<br/><br/>
<br/><br/>
<div class="jumbotron center vertical-center">
  <h2>Students</h2><br/>
  <table class="table">


    <th class="text-center">Name</th>
    <th class="text-center">Student Id</th>
    <th class="text-center">Email</th>


    <% @course.students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td> <%= student.student_id %></td>
          <td> <%= mail_to(student.email) %></td>
          <td>  <%= link_to 'Destroy', course_student_delete_student_path(@course, student), method: :delete, data: {confirm: 'Are you sure?'}, style: 'color:#FFFFFF', class: 'btn btn-danger' %> </td>

        </tr>
    <% end %>

  </table>
</div>
<%= link_to 'Add Students', edit_course_path(@course), :class => 'btn btn-primary', :style => 'color:#FFFFFF; float: right' %>


<br/><br/><br/>